FROM mcr.microsoft.com/devcontainers/python:3.10

WORKDIR /workspaces/boilerplate-medical-data-visualizer

COPY ../requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt